---
title:  "REQUERIMENTO DE GRAUS-DIAS PARA O FLORESCIMENTO E MATURAÇÃO DO ARROZ (*Oryza*   *sativa*
  L.) IRRIGADO E TERRAS ALTAS NO BRASIL"
author: "Gutemberg Resende Honorio Filho"
date: "25/08/2020"
output: html_document
           
---
Para acessar o script desta analise acesse [repositório github](<https://github.com/GutembergHonorio/Arroz_analise.git>)

```{r , include=F}
knitr::opts_chunk$set(warning = F, message = F)
```

```{r Diretório, include=FALSE} 
# DIRETÓRIO DOS DADOS 


## Carregue estes dados antes de manipular os demais aquivos filhos:


Caminho_dos_dados <- file.path("C:","Users","Gutemberg","Desktop","Mestrado","Dados da Dicertação","Dados Brutos","Merge_1980_2018.csv")
Tabelabruta<- read.csv(Caminho_dos_dados, header = TRUE, sep = ";", stringsAsFactors = FALSE) # tabela com os dados originais

### Tabelas acessório
     
TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED")
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND")
```

# Pacotes necessários
```{r Pacotes}

library(tidyverse)
library(rmarkdown)

library(xda)

library(geobr)
library(ggplot2)
library(ggspatial)
library(spatstat)

library(gridExtra) 
library(Hmisc)
library(PerformanceAnalytics)
```

# Analise descritiva dos dados

```{r , child = c('Descri.Rmd')}
# consultar arquivo Descri.Rmd

``` 
  
# Distribuição geografica e temporal dos ensáios
  
```{r , child = c('Geoesp.Rmd')}
# consultar arquivo Geoesp.Rmd

```  
  
  
# Determinação da temperatura ótima
  
```{r , child = c('Topt.Rmd')}
# consultar arquivo Topt.Rmd

```

# Matrix de correlação
  
```{r ,  child = c('Mcorr.Rmd')}
# consultar arquivo Mcorr.Rmd
```