---
output: html_document
---
```{r , include=F}
knitr::opts_chunk$set(warning = F, message = F)
```
```{r Diretório, include=FALSE} 
# DIRETÓRIO DOS DADOS 


## Carregue estes dados antes de manipular os demais aquivos filhos:


Caminho_dos_dados <- file.path("C:","Users","Gutemberg","Desktop","Mestrado","Dados da Dicertação","Dados Brutos","Merge_1980_2018.csv")
Tabelabruta<- read.csv(Caminho_dos_dados, header = TRUE, sep = ";", stringsAsFactors = FALSE) # tabela com os dados originais

### Tabelas acessório
     
TabelabrutaIRR = subset(Tabelabruta, SIST_CULT == "IRRIGATED")
TabelabrutaTA = subset(Tabelabruta, SIST_CULT == "UPLAND")
```

```{r , include=F}
# Pacotes necessários

if(!require(tidyverse))
  install.packages("tidyverse")
if(!require(gridExtra))
  install.packages("gridExtra")
#Obs.: Caso queira instalaro o pacote XDA é necessário instalar os pacotes abaixo:
if(!require(devtools)) 
  install.packages("devtools")
if(!require(xda)) 
  install_github("ujjwalkarn/xda")
library(rmarkdown)

```
  
      
## Arroz irrigado
```{r Tabelas acessório Irrigado, include=FALSE}


dadosIRR<- TabelabrutaIRR[,c(6,	7,	8,	21,	22,	23,	24,	25,	27,	60,	62,	63,	64,	
                             65,	66,	67,	68,	72,	73,	74,	75,	76,	77,	78,	79,	
                             80,	81,	82,	83,	84,	85,	86,	87,	88,	89,	90,	91,	
                             92,	93,	94,	95,	96,	97,	98,	99,	100,	101,	102,
                             103,	104,	105,	106,	107,	108,	109,	110,
                             111,	112,	113,	114,	115
)] 
names(dadosIRR)<- c("latitude",	"longitude",	"Altitude",	"Produtividade ",	
                    "Data de Florescimento (DAE)",	"Altura da planta",
                    "Ciclo total da planta",	"Acamamento",	"Vigor",	"Ano do Plantio",	
                    "Data de Florescimento estimado",	"Data de Florescimento médio",	
                    "Iniciação da panícula estimada",	"Iniciação da primeira panícula",	
                    "Maturação fisiológica",	"Maturação fisiológica estimada",	
                    "Maturação fisiológica máxima",	"Temperatura máxima no ciclo da cultura",
                    "Temperatura mínima no ciclo da cultura",	
                    "Temperatura média no ciclo da cultura",	
                    "Temperatura máxima na iniciação da panícula",
                    "Temperatura máxima no florescimento",	"Temperatura máxima no período vegetativo",	
                    "Temperatura máxima acumulada no período vegetativo",	"Temperatura máxima no período reprodutivo",
                    "Temperatura máxima acumulada no período reprodutivo",
                    "Temperatura máxima no período de enchimento de grãos",	
                    "Temperatura máxima acumulada no período de enchimento de grãos",	
                    "Valor máximo da temperatura mínima no ciclo da cultura ",
                    "Valor mínima da temperatura mínima no ciclo da cultura",	
                    "Valor médio da temperatura mínima no ciclo da cultura",	
                    "Valor da temperatura mínima durante a ocorrência da iniciação da panicula",
                    "Valor da temperatura mínima durante a ocorrência do florecimento",
                    "Temperatura mínima no período vegetativo",	
                    "Temperatura mínima acumulada no  período vegetativo",	
                    "Temperatura mínima no período reprodutivo",	
                    "Temperatura mínima acumulada no período reprodutivo",	
                    "Temperatura mínima no período do enchimento de grãos",	
                    "Temperatura mínima acumulada no períodode enchimento de grãos",
                    "Precipitação acumulada no ciclo da cultura",	"Precipitação acumulada no período vegetativo",	
                    "Precipitação acumulada no períodoreprodutivo",	
                    "Precipitação acumulada no período de enchimento de grãos",	
                    "Radiação acumulada no ciclo da cultura",	"Radiação acumulada no período vegetativo",	
                    "Radiação acumulada no período reprodutivo",	"Radiação acumulada no período de enchimento de grãos",
                    "Umidade média no ciclo da cultura",	"Umidade no periodo de florescimento ",	
                    "Umidade no período vegetativo",	"Umidade no período reprodutivo",	
                    "Umidade no período de enchimento de grãos",	"Vento médio no ciclo da cultura",	
                    "Vento no periodo de florescimento",	"Vento no período vegetativo",	"Vento no período reprodutivo",	
                    "Vento no período de enchimento de grãos",	"Graus dias acumulado do plantio a iniciação da panicula",
                    "Graus dias acumulado da iniciação da panicula ao florecimento",
                    "Graus dias acumulado do florecimento a maturação fisiológica",
                    "Graus dias acumulado no ciclo da cultura")
```

```{r Tabela exploratória IRR, echo=FALSE}
# Nessa parte é utilizado o pacote XDA



Descritivo_IRR<-numSummary(dadosIRR)
paged_table(Descritivo_IRR)
```
  
## Arroz terras altas
```{r Tabelas acessório Terras altas, include=FALSE}

dadosTA<- TabelabrutaTA[,c(6,	7,	8,	21,	22,	23,	24,	25,	27,	60,	62,	63,	64,	
                           65,	66,	67,	68,	72,	73,	74,	75,	76,	77,	78,	79,	
                           80,	81,	82,	83,	84,	85,	86,	87,	88,	89,	90,	91,	
                           92,	93,	94,	95,	96,	97,	98,	99,	100,	101,	102,
                           103,	104,	105,	106,	107,	108,	109,	110,
                           111,	112,	113,	114,	115
)] 

names(dadosTA)<- c("latitude",	"longitude",	"Altitude",	"Produtividade ",	
                    "Data de Florescimento (DAE)",	"Altura da planta",
                    "Ciclo total da planta",	"Acamamento",	"Vigor",	"Ano do Plantio",	
                    "Data de Florescimento estimado",	"Data de Florescimento médio",	
                    "Iniciação da panícula estimada",	"Iniciação da primeira panícula",	
                    "Maturação fisiológica",	"Maturação fisiológica estimada",	
                    "Maturação fisiológica máxima",	"Temperatura máxima no ciclo da cultura",
                    "Temperatura mínima no ciclo da cultura",	
                    "Temperatura média no ciclo da cultura",	
                    "Temperatura máxima na iniciação da panícula",
                    "Temperatura máxima no florescimento",	"Temperatura máxima no período vegetativo",	
                    "Temperatura máxima acumulada no período vegetativo",	"Temperatura máxima no período reprodutivo",
                    "Temperatura máxima acumulada no período reprodutivo",
                    "Temperatura máxima no período de enchimento de grãos",	
                    "Temperatura máxima acumulada no período de enchimento de grãos",	
                    "Valor máximo da temperatura mínima no ciclo da cultura ",
                    "Valor mínima da temperatura mínima no ciclo da cultura",	
                    "Valor médio da temperatura mínima no ciclo da cultura",	
                    "Valor da temperatura mínima durante a ocorrência da iniciação da panicula",
                    "Valor da temperatura mínima durante a ocorrência do florecimento",
                    "Temperatura mínima no período vegetativo",	
                    "Temperatura mínima acumulada no  período vegetativo",	
                    "Temperatura mínima no período reprodutivo",	
                    "Temperatura mínima acumulada no período reprodutivo",	
                    "Temperatura mínima no período do enchimento de grãos",	
                    "Temperatura mínima acumulada no períodode enchimento de grãos",
                    "Precipitação acumulada no ciclo da cultura",	"Precipitação acumulada no período vegetativo",	
                    "Precipitação acumulada no períodoreprodutivo",	
                    "Precipitação acumulada no período de enchimento de grãos",	
                    "Radiação acumulada no ciclo da cultura",	"Radiação acumulada no período vegetativo",	
                    "Radiação acumulada no período reprodutivo",	"Radiação acumulada no período de enchimento de grãos",
                    "Umidade média no ciclo da cultura",	"Umidade no periodo de florescimento ",	
                    "Umidade no período vegetativo",	"Umidade no período reprodutivo",	
                    "Umidade no período de enchimento de grãos",	"Vento médio no ciclo da cultura",	
                    "Vento no periodo de florescimento",	"Vento no período vegetativo",	"Vento no período reprodutivo",	
                    "Vento no período de enchimento de grãos",	"Graus dias acumulado do plantio a iniciação da panicula",
                    "Graus dias acumulado da iniciação da panicula ao florecimento",
                    "Graus dias acumulado do florecimento a maturação fisiológica",
                    "Graus dias acumulado no ciclo da cultura")

```

```{r Tabela exploratória TA, echo=FALSE}
# Nessa parte é utilizado o pacote XDA

Descritivo_TA<-numSummary(dadosTA)
paged_table(Descritivo_TA)
```

## Boxplots das principais variáveis

```{r Boxplots, echo=FALSE, fig.align='center', out.width='100%', fig.asp=0.6, fig.width=9}


rotulos<-c( "latitude",	"longitude",	"Altitude",	"Produtividade ",	
            "Data de Florescimento (DAE)",	"Altura da planta",
            "Ciclo total da planta",	"Acamamento",	"Vigor",	"Ano do Plantio",	
            "Data de Florescimento estimado",	"Data de Florescimento médio",	
            "Iniciação da panícula estimada",	"Iniciação da primeira panícula",	
            "Maturação fisiológica",	"Maturação fisiológica estimada",	
            "Maturação fisiológica máxima",	"Temperatura máxima no ciclo da cultura",
            "Temp. mínima no ciclo da cultura",	
            "Temp. média no ciclo da cultura",	
            "Temp. máxima na iniciação da panícula",
            "Temp. máxima no florescimento",	"Temperatura máxima no período vegetativo",	
            "Temp. máxima acumulada no período vegetativo",	"Temperatura máxima no período reprodutivo",
            "Temp. máxima acumulada no período reprodutivo",
            "Temp. máxima no período de enchimento de grãos",	
            "Temp. máxima acumulada no período de enchimento de grãos",	
            "Valor máximo da temperatura mínima no ciclo da cultura ",
            "Valor mínima da temperatura mínima no ciclo da cultura",	
            "Valor médio da temperatura mínima no ciclo da cultura",	
            "Valor da temperatura mínima durante a ocorrência da iniciação da panicula",
            "Valor da temperatura mínima durante a ocorrência do florecimento",
            "Temp. mínima no período vegetativo",	
            "Temp. mínima acumulada no  período vegetativo",	
            "Temp. mínima no período reprodutivo",	
            "Temp. mínima acumulada no período reprodutivo",	
            "Temp. mínima no período do enchimento de grãos",	
            "Temp. mínima acumulada no períodode enchimento de grãos",
            "Precip. acumulada no ciclo da cultura",	"Precip. acumulada no período vegetativo",	
            "Precip. acumulada no períodoreprodutivo",	
            "Precip. acumulada no período de enchimento de grãos",	
            "Radiação acumulada no ciclo da cultura",	"Radiação acumulada no período vegetativo",	
            "Radiação acumulada no período reprodutivo",	"Radiação acumulada no período de enchimento de grãos",
            "Umidade média no ciclo da cultura",	"Umidade no periodo de florescimento ",	
            "Umidade no período vegetativo",	"Umidade no período reprodutivo",	
            "Umidade no período de enchimento de grãos",	"Vento médio no ciclo da cultura",	
            "Vento no periodo de florescimento",	"Vento no período vegetativo",	"Vento no período reprodutivo",	
            "Vento no período de enchimento de grãos",	"Graus dias acumulado do plantio a iniciação da panicula",
            "Graus dias acumulado da iniciação da panicula ao florecimento",
            "Graus dias acumulado do florecimento a maturação fisiológica",
            "Graus dias acumulado no ciclo da cultura"
)
Rotulos2<-c("Graus",	"Graus",	"metros ao nivel do mar",	"kg/ha",	
            "Dias após a emergência",	"Altura (cm)",	"Dias",	"",	
            "",	"",	"Dias após a emergência",	"Dias após a emergência",	
            "Dias após a emergência",	"Dias após a emergência",	"Dias após a emergência",	
            "Dias após a emergência",	"Dias após a emergência",	"Temperatura (ºC)",	
            "Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",
            "Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	
            "Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	
            "Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	
            "Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",	"Temperatura (ºC)",
            "Temperatura (ºC)",	"Precipitação (mm)",	"Precipitação (mm)",	"Precipitação (mm)",
            "Precipitação (mm)",	"",	"",	"",	"",	"Umidade relativa (%UR)",	"Umidade relativa (%UR)",
            "Umidade relativa (%UR)",	"Umidade relativa (%UR)",	"Umidade relativa (%UR)",	"km/h",
            "km/h",	"km/h",	"km/h",	"km/h",	"ºC dia",	"ºC dia",	"ºC dia",	"ºC dia")


for(i in 1:31) {
  resumoDadosIRR <- tableGrob(summary(dadosIRR[i]), cols = "Irrigado") 
  resumoDadosTA <- tableGrob(summary(dadosTA[i]),cols = "Terras altas")
  
  dadosNum <- ggplot (data = dadosIRR) +
    geom_boxplot(aes(y= dadosIRR[,i], x= "Irr."), data = dadosIRR, color= "blue")+
    geom_boxplot(aes(y= dadosTA[,i], x= "T. a."), data = dadosTA, color= "#EA6E16")+
    labs(x = rotulos[i], y=Rotulos2[i] )
  ResumoDadosIRR <- tableGrob(summary(dadosIRR[i+30]), cols = "Irrigado") 
  ResumoDadosTA <- tableGrob(summary(dadosTA[i+30]),cols = "Terras altas")
  
  DadosNum <- ggplot (data = dadosIRR) +
    geom_boxplot(aes(y= dadosIRR[,i+30], x= "Irr."), data = dadosIRR, color= "blue")+
    geom_boxplot(aes(y= dadosTA[,i+30], x= "T. a."), data = dadosTA, color= "#EA6E16")+
    labs(x = rotulos[i], y=Rotulos2[i+30] )
  
  
  Boxplot_por_sist_cult1<-grid.arrange(resumoDadosIRR, dadosNum,resumoDadosTA ,ResumoDadosIRR, DadosNum,ResumoDadosTA , ncol=6)
  
  
}
rm(ResumoDadosIRR)
rm(ResumoDadosTA)
rm(resumoDadosIRR)
rm(resumoDadosTA)
rm(dadosNum)
rm(DadosNum)
rm(Rotulos2)
rm(rotulos)
rm(i)
```